name: maraya_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  permission_handler: ^8.3.0
  email_validator: ^2.1.17
  oktoast: ^3.3.0
  image_picker: ^0.8.5+3
  image_cropper: ^1.4.1
  flutter_multi_formatter: ^2.5.8
  persistent_bottom_nav_bar: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  keyboard_actions: ^3.4.7
  flutter_datetime_picker: ^1.5.1
  drop_down_list: ^0.0.4
  dropdown_button2: ^1.8.9
  flutter_launcher_icons: ^0.10.0
  flutter_screenutil: ^5.5.4
  flutter_translate: ^4.0.3
  flutter_slider_drawer: ^2.1.2
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.7
  infinite_scroll_pagination: ^3.2.0
  timeago: ^3.3.0
  uuid: ^3.0.7
  pull_to_refresh: ^2.0.0
  dotted_border: ^2.0.0+3
  slide_drawer: ^1.0.3
  lottie: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.0.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.10
  flutter_slide_drawer: ^1.0.3
  overlay_group_avatar: ^0.0.4
  age_calculator: ^1.0.0
  photo_view: ^0.13.0
  file_picker: ^4.6.0
  intl: ^0.17.0
  bottom_picker: ^2.3.2
  encrypt: ^5.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_localization: ^0.1.10
  intl_phone_field: ^3.0.0
  carousel_slider: ^4.0.0
  country_code_picker: ^3.0.0
  country_picker: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/i18n/

  fonts:
    - family: clashDisplayBold
      fonts:
        - asset: assets/fonts/ClashDisplayBold.otf
    - family: clashDisplayExtraLight
      fonts:
        - asset: assets/fonts/ClashDisplayExtraLight.otf
    - family: clashDisplayLight
      fonts:
        - asset: assets/fonts/ClashDisplayLight.otf
    - family: clashDisplayMedium
      fonts:
        - asset: assets/fonts/ClashDisplayMedium.otf
    - family: clashDisplayRegular
      fonts:
        - asset: assets/fonts/ClashDisplayRegular.otf
    - family: clashDisplaySemiBold
      fonts:
        - asset: assets/fonts/ClashDisplaySemiBold.otf

    - family: almarenaBold
      fonts:
        - asset: assets/fonts/Almarena-Bold.otf
    - family: almarenaDisplayBold
      fonts:
        - asset: assets/fonts/Almarena-Display-Bold.otf
    - family: almarenaDisplayLight
      fonts:
        - asset: assets/fonts/Almarena-Display-Light.otf
    - family: almarenaDisplayRegular
      fonts:
        - asset: assets/fonts/Almarena-Display-Regular.otf
    - family: almarenaLight
      fonts:
        - asset: assets/fonts/Almarena-Light.otf
    - family: almarenaRegular
      fonts:
        - asset: assets/fonts/Almarena-Regular.otf
